### ISSUE TITLE
How to get video duration

### ISSUE THREAD

**Issue by siremilomir** [u-wave/react-vimeo#181]
Hi, I'm using this component and I'm wondering
is it possible to get the duration for each video and print those values right next to the video title in the sidebar (similar to your demo example)
![video_duration](https://user-images.githubusercontent.com/6877309/156144402-0e8ae1cf-2a7d-48b7-bfcd-db46c5d4261e.png)

Thanks.

**Comment by goto-bus-stop** [comment]
It's possible to retrieve the duration of a video with this library but it requires you to actually mount the component and load the video, so it's not the right fit for your use case. I would look into a vimeo HTTP API library to fetch the duration of videos instead, maybe even do it once on the server side and save them because the vimeo API might not be super fast (maybe it is fast, I don't know, but probably not as fast as your own database is).
