### ISSUE TITLE
Add showWatchLater to props

### ISSUE THREAD

**Issue by bennik88** [u-wave/react-vimeo#206]
Problem:
I can't find an option to set `showLike`, `showWatchLater`, `showVimeoLogo` or `showShare `with props. It would be nice to activate or reactivate them on need like with the already existing prop `showPortrait`.

I can't find an option to set disable these within the component. Is there any option I'm missing to do so without setting this up on vimeo.com account/videos/ setting?

**Comment by goto-bus-stop** [comment]
the `showPortrait`, `showByline` and `showTitle` props correspond to embed options: https://github.com/vimeo/player.js#embed-options

AFAICT such options do not exist for watch later, the logo, or sharing. If there are options for them in the vimeo player.js SDK, we should expose them, but otherwise it's not possible.
